simplesocial/accounts/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views


app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUp.as_view(), name='signup'),
]

simplesocial/posts/urls.py
from django.urls import path
from . import views

app_name='posts'

urlpatterns = [
    path('', views.PostList.as_view(), name="all"),
    path("new/", views.CreatePost.as_view(), name="create"),
    path("by/<username>/",views.UserPosts.as_view(),name="for_user"),
    path("by/<username>/<int:pk>/",views.PostDetail.as_view(),name="single"),
    path("delete/<int:pk>/",views.DeletePost.as_view(),name="delete"),
]

simplesocial/simplesocial/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('test/', views.TestPage.as_view(), name='test'),
    path('thanks/', views.ThanksPage.as_view(), name='thanks'),
    path('posts/', include('posts.urls', namespace='posts')),
    path('groups/', include('groups.urls', namespace='groups')),
]

simplesocial/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Star Social</title>

    <!-- Bootstrap 5 CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css" rel="stylesheet">

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'simplesocial/css/master.css' %}">

  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark" role="navigation" id="navbar">
      <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}">Star Social</a>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
          aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
          <ul class="navbar-nav">
            {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'posts:create' %}">Post</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'groups:all' %}">Groups</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'groups:create' %}">Create Group</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:logout' %}">Log out</a>
              </li>
            {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'groups:all' %}">Groups</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:login' %}">Log in</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:signup' %}">Sign up</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>

    <div class="container mycontent">
      {% block content %}
      {% endblock %}
    </div>

    <canvas id="canvas"></canvas>

    <script src="{% static 'simplesocial/js/master.js' %}" type="text/javascript"></script>

    <!-- Bootstrap 5 JS Bundle -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-JTj6JjI5Q1La2Q5RVu5a6I95MTYSCXMzshI1Kg+tqO7yZukKkQz8eOagJ8i5r/TO"
      crossorigin="anonymous"></script>

  </body>
</html>

simplesocial/templates/index.html
{% extends 'base.html' %}

{% block content %}
    <h1>Welcome to Star Social</h1>
{% endblock %}

simplesocial/templates/test.html
{% extends 'base.html' %}
{% block content %}

<h1>You are now logged in!</h1>

{% endblock %}

simplesocial/templates/thanks.html
{% extends 'base.html' %}

{% block content %}

<h1>Thanks for visiting!</h1>


{% endblock %}